inet4 compatibility (wischhof, kallies): achieves basic compatiblity with inet4
Squashed commit of the following:

commit 8ac5ac5f9a4dd3aea0348adc9ce5a97195f60217
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Fri Oct 4 14:02:29 2019 +0200

    moved debug output to EV

commit 9eaf16fa517823fa5312fa15998668d02d8f1eb2
Author: odom11 <foo@bar.com>
Date:   Thu Oct 3 17:07:57 2019 +0200

    - comment files replaced by TODO in base directory
    - LteFeedback output reenabled
    - minor refactoring of LteFeedback

commit ca7338080a1354efd0580f5558d7762628610961
Author: odom11 <foo@bar.com>
Date:   Thu Oct 3 14:30:43 2019 +0200

    compatibility layer removed

commit 554accc13f0a9a15e4db3f68346f2196d6896a5e
Author: odom11 <foo@bar.com>
Date:   Sun Sep 29 18:08:22 2019 +0200

    replaced simple compatibility layer dependencies with inet dependencies and deleted corresponding compatibility files

commit 95e86c01bc02e2dafbc943b35fd849b3dbf9cf69
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu Sep 26 14:21:52 2019 +0200

    basic renaming of field names in order to match inet4

commit 7d78cd2457ff8734280fb0c483525b0f471273ac
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu Sep 26 13:44:14 2019 +0200

    parameter renaming to get tutorial and demo simulations working

commit a2b3cc373e7cc60d3753c4ec9eedd9a4d6feb0b1
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu Sep 26 13:06:49 2019 +0200

    minor fixes to get Multicell and ExtMulticell (tutorial) working

    type of initial position is now double
    type of application set correctly

commit 85d407322e4aea0d9c1febe2861300eaace9ae1b
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu Sep 26 12:43:41 2019 +0200

    Added separate Lte Uu - required to dispatch Uu packet in eNodeB

    In order to allow the MessageDispatcher at nl in the eNodeB to send all IP packets received on the Uu link to the traffic filter, a separate protocol identifier was introduced.

commit 06e9731b7bdb71f78048b0b62fcef0a97a3d6f51
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Tue Sep 24 10:23:10 2019 +0200

    correct initstages for LteNic

commit c3c8b47f37de93447e531f7c7ec02461b032ca11
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Mon Sep 23 15:31:14 2019 +0200

    fix: arrival time of VoIP packet was not set correctly

commit 144c974f2a1cd32f290274d56d37be1efb8b2afb
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Mon Sep 23 15:13:01 2019 +0200

    removed debug output: received packets

commit b190afcc6fffec38e392880c7f539db91fd7fba6
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Mon Sep 23 13:38:38 2019 +0200

    fixes for SingleCellUplink Scenario

    add DispatchProtocolReq for packets to eNB
    add PacketProtocolTag for packets forwarded from pgw
    upperLayerOut port of LteNic now connected directly to trafficFlowFilter.internetFilterGateIn

commit b75b48e97070246dd965a2b8032bc340cfec262f
Merge: 77fdd32 8aae3dc
Author: Wischhof, Lars <wischhof@hm.edu>
Date:   Thu Sep 19 13:37:00 2019 +0200

    Merge branch 'hm_inet4_compatible_wip_packatif' into 'hm_inet4_compatible'

    next step towards an inet4 port: adapatation to inet::Packet

    See merge request rover/simulte!2

commit 8aae3dc2f48a8684fbf03c5817e606000c10115a
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu Sep 19 13:31:02 2019 +0200

    fix memory leak: delete original packet after encapsulating their data in GTP message

commit ba18ee31430a990131cede1dd53f67a7225e6e84
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu Sep 19 13:22:14 2019 +0200

    fix: keep correct name of packet even when transferred via GTP

commit 21281abb2c5178d167e9491725f1706e842ae196
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu Sep 19 13:06:10 2019 +0200

    added DispatchProtocolReq and InterfaceInd in LteIp for correct  msg dispatching

commit e914e9501dba0c7db25c4295bfc7c79bbbfb8ec3
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu Sep 19 13:05:05 2019 +0200

    fix: VoIP receiver adaptation inet::packet (still not using socket if)

commit 55539fc0f2598962a43acf39d5a5aa5c92885b70
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu Sep 19 10:49:28 2019 +0200

    remove InterfaceReq upon reception in LteNic (i.e. when interface has been reached)

commit 0760b26935a7e14e8918a0c593b11ebd5a34d553
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu Sep 19 10:09:47 2019 +0200

    add InterfaceReq so that nl dispatcher can determine the outgoing interface on an eNB

commit 0839b8e56428fbf94378b346a43965808ff2b367
Merge: cc4a3f1 c082b6e
Author: Wischhof, Lars <wischhof@hm.edu>
Date:   Wed Sep 18 22:26:29 2019 +0200

    Merge branch 'hm_inet4_compativle_wip_autoconvert' into 'hm_inet4_compatible_wip_packatif'

    Hm inet4 compatible autoconvert

    See merge request rover/simulte!1

commit c082b6e102565241d8ee88d91afaa19dd1354520
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Wed Sep 18 22:21:49 2019 +0200

    fix: cannot simply add header in front since packet has already partially be decapsulated - convert to new packet and forward instead

commit cc74272d1313dccf68f1adff4233df840cd971d6
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Wed Sep 18 15:25:27 2019 +0200

    renaming and manual fixes for INET 4 (after autoconvert, compilable again)

commit cc4a3f12f52298ff69eaddb95435af560be31de6
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Tue Sep 17 21:19:07 2019 +0200

    next step in converting to inet::packet - most adaptations to new
    message compiler but still does not compile successfully

commit 3f83633c69762073b2fae5643ceb339b21d1eb67
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Sun Jul 21 16:47:34 2019 +0200

    WIP: changes for new message compiler (--msg6) - required in order to use inet::Packet

commit 0f488c852fc6dbeae9e986231eaff698ccdfee91
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Sun Jul 21 16:39:05 2019 +0200

    PgwStandard structure fixed

commit 77fdd32e9c15bf6b2a934abfd40aebbbe58f5cb3
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Fri Jul 12 10:24:22 2019 +0200

    quick hack to convert inet::Packet to omnetpp::cPacket and vice versa

    This is a quick and ugly hack to get simulte running again, in the long term the simulte components need to be refactored to be based on inet::Packet instead of omnetpp::cPacket

commit 3c07f33958232de03965103d1f82be62fc91eeef
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu Jul 11 15:37:23 2019 +0200

    WIP: Adaptation of packet processing in GtpUser, TrafficFlowFilter

commit 03c92020a0b22f46d97a76a941ff3ea7a6a5221d
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Wed Jul 10 13:57:28 2019 +0200

    refactoring of eNodeB/eNBpp modules, network interface registration fixed

commit 1f22a3040a9a6b1439563dbbd87e298e4c4e9905
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Sat Jun 15 06:39:01 2019 +0200

    bugfix: added missing connections to of tn dispatcher to ipv4 sublayer

commit 79fc0e616a4d51e96051c63eb826e3eb255a604b
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Sat Jun 15 02:07:14 2019 +0200

    fix of UE and eNodeB structure, correct init stages

commit 79356b5c6011f1a82a7e7bf25b4082e28e94048f
Merge: fc7a49b 0955016
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Fri Jun 14 14:16:41 2019 +0200

    Merge branch 'hm_inet4_compatible' of ssh://sam-dev.cs.hm.edu:5022/rover/simulte into hm_inet4_compatible

commit fc7a49b25b7dc844486b8bd6b7af928cc6cbb7ec
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Fri Jun 14 14:14:24 2019 +0200

    fix: initialization of IP2lte

commit 09550169e7dedc3ae885bef4252e1c8e3d0b5495
Author: kallies <kallies@hm.edu>
Date:   Fri Jun 14 13:14:18 2019 +0200

    removed deprecation, added ltex2manager

commit 513a4554d756d89a80e42379f5fd0bb9b73f10ca
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Wed Jun 12 22:45:33 2019 +0200

    added empty implementations of ILifeCycle in order to make LteIp compileable again - still need to be implemented when remaining parts of LteIp are finished

commit 677085c16b52d61ef9287ae6be5984444130ccc9
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Tue Jun 4 11:03:46 2019 +0200

    fix: segv when lte interface is not available

commit e9ecdc09fd750c98655d3c025a87056e4d424ce1
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Mon Jun 3 22:27:06 2019 +0200

    WIP: first steps fix the tutorial scenario: ini file updated to new inet4 structure, .ned files fixed

commit 379f383ad9a9a8634d4fc3904d06715446b0c846
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Fri May 31 08:17:42 2019 +0000

    fixed first set of compile warnings: unused variables, missing initializations and return values (WIP, still many warnings remain...)

commit 1a9b081682cfe4aecd3d18e7159eb7a44322c38e
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Fri May 31 07:46:10 2019 +0000

    WIP: .ned files adapted for new message dispatcher logic and generia IApp interface - untested, simulation ini files still need to be adapted

commit d683052ec2be9e379a1da4fe8ece0012a605ae14
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Fri May 31 07:01:05 2019 +0000

    minor fix: possible uninitizlized use of direction in LteDrr

commit d1aa4d689bb8caa7d62e4445b22c0e2874c5cfcf
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu May 30 22:04:08 2019 +0200

    fix: capital case in .ned files

commit 375e161514dfe9a8d066c6d69caf3b0b8b66c5e8
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu May 30 19:27:31 2019 +0000

    fix: cPacket now in omnetpp namespace

commit bef5d193bff9d1bf031afa28c8abb9d71f1a186e
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu May 30 21:11:37 2019 +0200

    new layer names in inet4, ipv4 multicast and address changes

commit 03055710d6d4058c8a0c4a8b7a320a2f2ef1cb07
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu May 30 21:09:45 2019 +0200

    IPv4 configurator  was renamed in inet4- fix ned files

commit 9c27a97d7a703d3ef5ef84af4a86b4648b96dfe8
Author: Lars Wischhof <wischhof@ieee.org>
Date:   Thu May 30 21:08:38 2019 +0200

    fixed Makefile and buildspec: add new include folder

commit 7c74d1ed999ae74d871e73af1117785e49e4cd7f
Author: foobar <foo@bar>
Date:   Thu May 9 11:28:09 2019 +0200

    updated README

commit ca6f0eff152204cf413fb271a0bb8ee3d3206aa9
Author: foobar <foo@bar>
Date:   Thu May 9 10:11:59 2019 +0200

    ready for sharing

commit fca4fc8fddcfecc846eba6eac6326251ad9e69ef
Author: foobar <foo@bar>
Date:   Wed May 1 16:07:34 2019 +0200

    compiling, running, failing tests

commit 2ba3fe6f946bbe949b75acb12d861d02bd683abc
Author: foobar <foo@bar>
Date:   Tue Apr 23 16:03:47 2019 +0200

    'fixed' incorrect reference in x2/X2AppClient.cc refering to registerSignal. Unsure whether it is the correct reference. Changed references to functions which are marked deprecated in omnet

commit 267b9655749b0bb7a389b53627311b7efd6e1cda
Author: datAss <foobar@foo.com>
Date:   Fri Mar 29 13:30:25 2019 +0100

    compiling, but untested

commit ef8039ae7ed50f8dfa461d014b9b58590aa9faf5
Author: datAss <foobar@foo.com>
Date:   Fri Mar 29 11:45:59 2019 +0100

    added sendTo method to UDPSocket in compatibility layer

commit 0adb94139fdb652745ca023ecbcf7e4fa012f057
Author: datAss <foobar@foo.com>
Date:   Sat Mar 23 08:04:17 2019 +0100

    reverting to cPacket. It did end in tears

commit 0c80dd27de142a7d5f2a37f0d72b509046c975e7
Author: datAss <foobar@foo.com>
Date:   Thu Mar 14 10:58:00 2019 +0100

    modified sources in x2 folder fixing compilation errors. Broken output workaround

commit 54ea110ea445a59c4c403f38ef8f414ec29eca35
Author: datAss <foobar@foo.com>
Date:   Wed Mar 13 15:58:29 2019 +0100

    sources are modified up until x2 folder. Obscure compiler messages when compiling more than once with errors (see TODO

commit 31354bd05a1dd6a80d204ed77c74ee771526f742
Author: datAss <foobar@foo.com>
Date:   Mon Mar 11 18:53:44 2019 +0100

    adapted sources from stack folder

commit fb0113f3726cfeaea7b5fe3daffae0e923fbabb5
Author: datAss <foobar@foo.com>
Date:   Fri Mar 8 12:36:23 2019 +0100

    resolved stuff

commit 6f3d1e54f45d8736c47384d686f3e322130bb81d
Author: datAss <foobar@foo.com>
Date:   Wed Mar 6 17:25:46 2019 +0100

    modified LteIp.cc further. If stuff doesn't work in the future, look here (vast changes from inet3 to inet4)

commit 48bf8d658217a7fc680675882995c7551e86140b
Author: datAss <foobar@foo.com>
Date:   Mon Mar 4 17:30:05 2019 +0100

    derived SimuLTE packages from inet::Packet instead of omnet::cPacket. This will end in tears

commit deb7049dbba859565ded5c1be875f2fddee2380d
Author: datAss <foobar@foo.com>
Date:   Sat Mar 2 12:35:06 2019 +0100

    started adaptation of corenetwork/LteIp

commit d869c0afcc182a1496e8cfb22637520b265a7c4d
Author: datAss <foobar@foo.com>
Date:   Wed Feb 20 17:12:37 2019 +0100

    further fixing (hopefully it compiles one day

commit 9031178896495237777ed6fbe0f6e9224939637a
Author: datAss <foobar@foo.com>
Date:   Mon Feb 18 20:15:17 2019 +0100

    overhaul started

commit ba56250f24034b427e6f4c1246d7b615c1e0d40f
Author: datAss <foobar@foo.com>
Date:   Tue Jan 22 13:16:08 2019 +0100

    removed using namespace... from header files